remote_theme: pmarsceill/just-the-docs
title: "Exploding Bricks: Python Library"
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
